### ISSUE TITLE
SQL Injection Vulnerability

### ISSUE THREAD

**Issue by VFXGamer** [Pagasis/VaultDB#1]
Following lines of codes have SQL injection vulnerability.
https://github.com/Pagasis/VaultDB/blob/f31b6c9106a99ec07df2208e341a52da661586dd/vaultdb.py#L35
https://github.com/Pagasis/VaultDB/blob/f31b6c9106a99ec07df2208e341a52da661586dd/vaultdb.py#L47
https://github.com/Pagasis/VaultDB/blob/f31b6c9106a99ec07df2208e341a52da661586dd/vaultdb.py#L55
https://github.com/Pagasis/VaultDB/blob/f31b6c9106a99ec07df2208e341a52da661586dd/vaultdb.py#L63

**Comment by Pagasis** [comment]
#2 Error Fixed
