### ISSUE TITLE
Master Password Reset Feature

### ISSUE THREAD

**Issue by VFXGamer** [Pagasis/VaultDB#5]
Master Password Reset option can help in those cases where someone forgets their master password.

**Comment by ElyTgy** [comment]
@VFXGamer can you assign this to me?

**Comment by VFXGamer** [comment]
You wil have to ask @Pagasis

**Comment by ElyTgy** [comment]
@Pagasis I would love to work on this. Can you assign me the issue?

**Comment by Pagasis** [comment]
Yeah sure

**Comment by ElyTgy** [comment]
@Pagasis I made a pull requests and made some suggestions. Please have a look when you have the time.
